[workspace]
members = [
  "happ/zomes/profiles",
  "happ/zomes/profiles_integrity",
  "happ/zomes/projects",
  "happ/zomes/projects_integrity",
]
resolver = "2"

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace.dependencies]
hdi = "0.5.0-rc"
hdk = "0.4.0-rc"
holochain = { version = "0.4.0-rc" }
holo_hash = {version = "0.4.0-rc", features = ["encoding"]}
hdk_crud = { version = "0.14.0", features = ["no_example"] }